a=int(input('enter first number :'))
b=int(input('enter second number: '))
print('sum=',a+b)
print('difference=',a-b)
print('multiplication=',a*b)
print('division=',a/b)
print('modulous=',a%b)
print('first number is',a)
print('second number is',b)
